---
name: pdd
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  pdd:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - run: gem install pdd
      - run: pdd --format xml . | ( ! grep '<puzzle>' )
